import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ArrowRight, Check, CirclePlay, Sparkles, WandSparkles } from "lucide-react";
import { Link } from "wouter";
import ThemeToggle from "@/components/ThemeToggle";

const steps = [
  ["01", "Bentuk kreator Anda", "Tentukan persona, identitas visual, dan energi yang ingin dirasakan audiens Anda."],
  ["02", "Arahkan momennya", "Pilih latar, pakaian, pengambilan gambar, dan sudut UGC melalui kontrol kreatif yang terarah."],
  ["03", "Buat & sempurnakan", "Buat visual yang rapi, simpan prompt, dan bangun pustaka aset yang dapat digunakan kembali."],
];

export default function Home() {
  const { user, loading } = useAuth();
  return (
    <div className="min-h-screen overflow-hidden bg-[#f7f8f5] text-[#17211e]">
      <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <a href="/" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-[#17211e] text-[#d6f37b]"><Sparkles size={18} /></span><span>omni<span className="text-[#95ae42]">studio</span><sup className="ml-0.5 text-[9px]">AI</sup></span></a>
        <nav className="hidden items-center gap-8 text-sm text-[#5d6863] md:flex"><a href="#workflow" className="transition hover:text-[#17211e]">Alur kerja</a><a href="#why" className="transition hover:text-[#17211e]">Mengapa Omni</a></nav>
        <div className="flex items-center gap-3"><ThemeToggle />{loading ? <div className="h-10 w-24 animate-pulse rounded-full bg-[#e7ebe5] dark:bg-white/10" /> : user ? <Link href="/studio" className="rounded-full bg-[#17211e] px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-[#2c3b35]">Buka studio <ArrowRight className="ml-2 inline size-4" /></Link> : <button onClick={() => startLogin()} className="rounded-full bg-[#17211e] px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-[#2c3b35]">Masuk <ArrowRight className="ml-2 inline size-4" /></button>}</div>
      </header>

      <main>
        <section className="relative mx-auto grid max-w-7xl gap-14 px-6 pb-24 pt-14 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-20">
          <div className="absolute -left-44 -top-44 size-[36rem] rounded-full bg-[#e5f0a9]/55 blur-3xl" />
          <div className="relative z-10 max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#dce2d5] bg-white/60 px-3.5 py-2 text-xs font-medium text-[#64706a]"><span className="size-1.5 rounded-full bg-[#a4c64e]" /> Sistem kreatif untuk UGC modern</div><h1 className="max-w-xl text-5xl font-semibold leading-[.98] tracking-[-.055em] text-[#17211e] sm:text-7xl">Kreator berikutnya <span className="text-[#8ca93a]">sudah ada di sini.</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#64706a]">Buat karakter UGC virtual yang meyakinkan dengan arahan, detail, dan konsistensi yang layak untuk merek Anda.</p><div className="mt-9 flex flex-wrap items-center gap-3"><button onClick={() => user ? (window.location.href = "/studio") : startLogin()} className="rounded-full bg-[#17211e] px-6 py-3.5 text-sm font-semibold text-white shadow-xl shadow-[#17211e]/10 transition hover:-translate-y-0.5 hover:bg-[#2c3b35]">Buat karakter pertama Anda <ArrowRight className="ml-2 inline size-4" /></button><a href="#workflow" className="rounded-full px-5 py-3.5 text-sm font-semibold text-[#52615a] transition hover:bg-white">Lihat cara kerjanya <CirclePlay className="ml-2 inline size-4" /></a></div><div className="mt-10 flex items-center gap-6 text-xs text-[#77827c]"><span><Check className="mr-1 inline size-3.5 text-[#8ca93a]" /> Alur kerja berbasis prompt</span><span><Check className="mr-1 inline size-3.5 text-[#8ca93a]" /> Aset Anda, selalu milik Anda</span></div></div>
          <div className="relative z-10 mx-auto w-full max-w-[520px]"><div className="absolute -right-5 top-8 h-32 w-32 rounded-full bg-[#dce98a] blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/80 bg-[#dfe8cf] p-3 shadow-2xl shadow-[#26332c]/10"><div className="overflow-hidden rounded-[1.5rem] bg-[#c4d1b8]"><div className="flex items-center justify-between px-5 py-4 text-[10px] font-semibold tracking-[.16em] text-[#42534a]"><span>OMNI / KARAKTER 001</span><span className="rounded-full bg-white/40 px-2 py-1 tracking-normal">PRATINJAU LANGSUNG</span></div><div className="relative aspect-[.9] overflow-hidden bg-gradient-to-b from-[#b8c8b1] via-[#d4d9c1] to-[#eee5d6]"><div className="absolute left-1/2 top-[18%] h-[67%] w-[60%] -translate-x-1/2 rounded-[48%_48%_38%_38%] bg-[radial-gradient(circle_at_50%_22%,#e9b996_0_19%,transparent_20%),linear-gradient(90deg,#63483c,#bb8064_45%,#5d4036)] shadow-[inset_-20px_-15px_30px_rgba(44,25,18,.22)]" /><div className="absolute bottom-0 left-1/2 h-[42%] w-[85%] -translate-x-1/2 rounded-t-[50%] bg-[#667a70]" /><div className="absolute bottom-8 left-1/2 -translate-x-1/2 rounded-full bg-white/70 px-3 py-1.5 text-[10px] font-medium text-[#415047] backdrop-blur">Rekomendasi natural, langsung untuk Anda.</div></div></div><div className="flex items-center justify-between px-5 py-4 text-xs"><span className="font-semibold text-[#34433a]">Energi founder yang hangat</span><span className="text-[#78847d]">Potret / 9:16</span></div></div></div>
        </section>

        <section id="workflow" className="border-y border-[#e5e9e2] bg-white px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#8ca93a]">Cara yang lebih tenang untuk berkarya</p><h2 className="mt-3 max-w-lg text-4xl font-semibold tracking-[-.04em]">Dari brief kosong menjadi <span className="text-[#8ca93a]">rasa yang nyata.</span></h2></div><p className="max-w-sm text-sm leading-6 text-[#738079]">Pilihan terarah menggantikan rangkaian prompt tanpa akhir, sehingga setiap aset tetap memiliki ciri khas Anda.</p></div><div className="grid gap-4 md:grid-cols-3">{steps.map(([number, title, body]) => <div key={number} className="rounded-3xl bg-[#f6f8f3] p-7 transition hover:-translate-y-1"><span className="text-xs font-semibold text-[#a5bd5c]">{number}</span><h3 className="mt-12 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#738079]">{body}</p></div>)}</div></div></section>
        <section id="why" className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="rounded-[2rem] bg-[#17211e] p-8 text-white md:p-14"><div className="grid gap-12 md:grid-cols-[1fr_.8fr] md:items-end"><div><WandSparkles className="mb-7 size-7 text-[#d6f37b]" /><h2 className="max-w-xl text-4xl font-semibold tracking-[-.04em]">Partner kreatif yang mengingat setiap detail.</h2></div><p className="text-sm leading-7 text-[#bdc8bf]">Metadata prompt selalu tersimpan bersama setiap generasi. Buka kembali karakter, salin arahan yang sama, dan terus berkarya tanpa memulai dari awal.</p></div></div></section>
      </main>
      <footer className="mx-auto flex max-w-7xl justify-between px-6 pb-8 text-xs text-[#88938c] lg:px-10"><span>© 2026 Omni Studio AI</span><span>Dibuat untuk generasi kreator berikutnya.</span></footer>
    </div>
  );
}
