import { and, desc, eq, gte, lt, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { brandKits, calendarItems, generations, InsertBrandKit, InsertCalendarItem, InsertGeneration, InsertPlatformPreset, InsertPreset, InsertProject, InsertStoryboard, InsertStudioNotification, InsertUser, InsertVideoDraft, InsertVideoRender, platformPresets, presets, projects, storyboards, studioNotifications, users, videoDrafts, videoRenders } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch { _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; for (const field of ["name", "email", "loginMethod"] as const) { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } } values.lastSignedIn = user.lastSignedIn ?? new Date(); updateSet.lastSignedIn = values.lastSignedIn; if (user.role !== undefined || user.openId === ENV.ownerOpenId) { values.role = user.role ?? "admin"; updateSet.role = values.role; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listGenerations(userId: number, options?: { projectId?: number; useCase?: string; since?: Date }) { const db = await getDb(); if (!db) return []; const filters = [eq(generations.userId, userId)]; if (options?.projectId) filters.push(eq(generations.projectId, options.projectId)); if (options?.useCase) filters.push(eq(generations.useCase, options.useCase)); if (options?.since) filters.push(gte(generations.createdAt, options.since)); return db.select().from(generations).where(and(...filters)).orderBy(desc(generations.createdAt)); }
export async function createGeneration(input: InsertGeneration) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(generations).values(input); const id = Number(result[0].insertId); const created = await db.select().from(generations).where(eq(generations.id, id)).limit(1); return created[0]; }
export async function deleteGeneration(userId: number, id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(generations).where(and(eq(generations.id, id), eq(generations.userId, userId))); return { success: true as const }; }
export async function getOrCreateProject(userId: number, name: string, campaignNote: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = await db.select().from(projects).where(eq(projects.userId, userId)).orderBy(desc(projects.updatedAt)).limit(1); if (existing[0]) return existing[0]; const result = await db.insert(projects).values({ userId, name, campaignNote, progress: 0 }); const created = await db.select().from(projects).where(eq(projects.id, Number(result[0].insertId))).limit(1); return created[0]; }
export async function updateProject(userId: number, id: number, input: Pick<InsertProject, "name" | "campaignNote" | "progress">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(projects).set(input).where(and(eq(projects.id, id), eq(projects.userId, userId))); const updated = await db.select().from(projects).where(and(eq(projects.id, id), eq(projects.userId, userId))).limit(1); return updated[0]; }
export async function listProjects(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(projects).where(eq(projects.userId, userId)).orderBy(desc(projects.updatedAt)); }
export async function listPresets(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(presets).where(eq(presets.userId, userId)).orderBy(desc(presets.createdAt)); }
export async function createPreset(input: InsertPreset) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(presets).values(input); const created = await db.select().from(presets).where(eq(presets.id, Number(result[0].insertId))).limit(1); return created[0]; }
export async function updatePreset(userId: number, id: number, input: Pick<InsertPreset, "name" | "description" | "controlsJson">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(presets).set(input).where(and(eq(presets.id, id), eq(presets.userId, userId))); const updated = await db.select().from(presets).where(and(eq(presets.id, id), eq(presets.userId, userId))).limit(1); return updated[0]; }
export async function deletePreset(userId: number, id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.delete(presets).where(and(eq(presets.id, id), eq(presets.userId, userId))); return { success: true as const }; }
export async function getBrandKit(userId: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(brandKits).where(eq(brandKits.userId, userId)).orderBy(desc(brandKits.updatedAt)).limit(1); return result[0]; }
export async function upsertBrandKit(userId: number, input: Omit<InsertBrandKit, "userId" | "id" | "createdAt" | "updatedAt">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = await getBrandKit(userId); if (existing) { await db.update(brandKits).set(input).where(and(eq(brandKits.id, existing.id), eq(brandKits.userId, userId))); return getBrandKit(userId); } await db.insert(brandKits).values({ userId, ...input }); return getBrandKit(userId); }
export async function createStoryboard(input: InsertStoryboard) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(storyboards).values(input); const created = await db.select().from(storyboards).where(eq(storyboards.id, Number(result[0].insertId))).limit(1); return created[0]; }
export async function listStoryboards(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(storyboards).where(eq(storyboards.userId, userId)).orderBy(desc(storyboards.updatedAt)); }
export async function createCalendarItem(input: InsertCalendarItem) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(calendarItems).values(input); const created = await db.select().from(calendarItems).where(eq(calendarItems.id, Number(result[0].insertId))).limit(1); return created[0]; }
export async function listCalendarItems(userId: number, options?: { monthStart?: Date; monthEnd?: Date; channel?: string; status?: "draft" | "scheduled" | "published" }) { const db = await getDb(); if (!db) return []; const filters = [eq(calendarItems.userId, userId)]; if (options?.monthStart) filters.push(gte(calendarItems.scheduledFor, options.monthStart)); if (options?.monthEnd) filters.push(lt(calendarItems.scheduledFor, options.monthEnd)); if (options?.channel) filters.push(eq(calendarItems.channel, options.channel)); if (options?.status) filters.push(eq(calendarItems.status, options.status)); return db.select().from(calendarItems).where(and(...filters)).orderBy(calendarItems.scheduledFor); }
export async function updateCalendarItem(userId: number, id: number, input: Partial<Pick<InsertCalendarItem, "scheduledFor" | "channel" | "status">>) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(calendarItems).set(input).where(and(eq(calendarItems.id, id), eq(calendarItems.userId, userId))); const updated = await db.select().from(calendarItems).where(and(eq(calendarItems.id, id), eq(calendarItems.userId, userId))).limit(1); return updated[0]; }
export async function createVideoDraft(input: InsertVideoDraft) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(videoDrafts).values(input); const created = await db.select().from(videoDrafts).where(eq(videoDrafts.id, Number(result[0].insertId))).limit(1); return created[0]; }
export async function listVideoDrafts(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(videoDrafts).where(eq(videoDrafts.userId, userId)).orderBy(desc(videoDrafts.updatedAt)); }
export async function getNextVideoQueuePosition(userId: number) { const db = await getDb(); if (!db) return 1; const [result] = await db.select({ max: sql<number>`coalesce(max(${videoRenders.queuePosition}), 0)` }).from(videoRenders).where(and(eq(videoRenders.userId, userId), sql`${videoRenders.status} in ('queued', 'rendering')`)); return Number(result?.max ?? 0) + 1; }
export async function createVideoRender(input: InsertVideoRender) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(videoRenders).values(input); const created = await db.select().from(videoRenders).where(eq(videoRenders.id, Number(result[0].insertId))).limit(1); return created[0]; }
export async function listVideoRenders(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(videoRenders).where(eq(videoRenders.userId, userId)).orderBy(desc(videoRenders.createdAt)); }
export async function listQueuedVideoRenders(userId: number, limit = 10) { const db = await getDb(); if (!db) return []; return db.select().from(videoRenders).where(and(eq(videoRenders.userId, userId), eq(videoRenders.status, "queued"))).orderBy(videoRenders.queuePosition).limit(limit); }
export async function getActiveVideoRender(userId: number, excludeId?: number) { const db = await getDb(); if (!db) return undefined; const filters = [eq(videoRenders.userId, userId), sql`${videoRenders.status} = 'rendering'`]; if (excludeId) filters.push(sql`${videoRenders.id} <> ${excludeId}`); const result = await db.select().from(videoRenders).where(and(...filters)).orderBy(videoRenders.createdAt).limit(1); return result[0]; }
export async function getVideoRender(userId: number, id: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(videoRenders).where(and(eq(videoRenders.id, id), eq(videoRenders.userId, userId))).limit(1); return result[0]; }
export async function getVideoRenderByTaskUid(taskUid: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(videoRenders).where(eq(videoRenders.scheduleCronTaskUid, taskUid)).limit(1); return result[0]; }
export async function updateVideoRender(userId: number, id: number, input: Partial<Pick<InsertVideoRender, "operationName" | "platform" | "aspectRatio" | "durationSeconds" | "status" | "queuePosition" | "scheduleCronTaskUid" | "notificationSentAt" | "videoUrl" | "errorMessage">>) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(videoRenders).set(input).where(and(eq(videoRenders.id, id), eq(videoRenders.userId, userId))); return getVideoRender(userId, id); }
export async function createStudioNotification(input: InsertStudioNotification) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(studioNotifications).values(input); const created = await db.select().from(studioNotifications).where(eq(studioNotifications.id, Number(result[0].insertId))).limit(1); return created[0]; }
export async function listStudioNotifications(userId: number, unreadOnly = false) { const db = await getDb(); if (!db) return []; const filters = [eq(studioNotifications.userId, userId)]; if (unreadOnly) filters.push(sql`${studioNotifications.readAt} is null`); return db.select().from(studioNotifications).where(and(...filters)).orderBy(desc(studioNotifications.createdAt)).limit(30); }
export async function markStudioNotificationRead(userId: number, id: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(studioNotifications).set({ readAt: new Date() }).where(and(eq(studioNotifications.id, id), eq(studioNotifications.userId, userId))); return { success: true as const }; }
export async function getPlatformPreset(userId: number, platform: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(platformPresets).where(and(eq(platformPresets.userId, userId), eq(platformPresets.platform, platform))).limit(1); return result[0]; }
export async function listPlatformPresets(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(platformPresets).where(eq(platformPresets.userId, userId)).orderBy(platformPresets.platform); }
export async function upsertPlatformPreset(userId: number, input: Omit<InsertPlatformPreset, "userId" | "id" | "createdAt" | "updatedAt">) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = await getPlatformPreset(userId, input.platform); if (existing) { await db.update(platformPresets).set(input).where(and(eq(platformPresets.id, existing.id), eq(platformPresets.userId, userId))); return getPlatformPreset(userId, input.platform); } await db.insert(platformPresets).values({ userId, ...input }); return getPlatformPreset(userId, input.platform); }
