import { z } from "zod";
import { getRequestSessionToken } from "./_core/sessionToken";
import { createHeartbeatJob } from "./_core/heartbeat";
import { processVideoRenderTask } from "./videoQueue";
import { SOCIAL_PLATFORMS, VIDEO_DURATIONS } from "@shared/platforms";
import { COOKIE_NAME } from "@shared/const";
import { buildGenerationPrompt, StudioControls } from "@shared/prompt";
import { getSessionCookieOptions } from "./_core/cookies";
import { generateImage } from "./_core/imageGeneration";
import { invokeLLM } from "./_core/llm";
import { pollVeoRender, startVeoRender } from "./_core/videoGeneration";
import { storagePut } from "./storage";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { createCalendarItem, createGeneration, createPreset, createStoryboard, createStudioNotification, createVideoDraft, createVideoRender, deleteGeneration, deletePreset, getBrandKit, getNextVideoQueuePosition, getOrCreateProject, getVideoRender, listCalendarItems, listGenerations, listPlatformPresets, listPresets, listProjects, listStudioNotifications, listStoryboards, listVideoDrafts, listVideoRenders, markStudioNotificationRead, updateCalendarItem, updatePreset, updateProject, updateVideoRender, upsertBrandKit, upsertPlatformPreset } from "./db";

const controlsSchema = z.object({ persona: z.string().min(1).max(120), appearance: z.string().min(1).max(200), expression: z.string().min(1).max(120), outfit: z.string().min(1).max(160), setting: z.string().min(1).max(160), shotType: z.string().min(1).max(120), useCase: z.string().min(1).max(160) });
const framingSchema = z.enum(["Potret natural", "Close-up ekspresif", "Lifestyle sinematik", "Hero produk"]);
const directionEntrySchema = z.object({ source: z.string().min(1).max(40), label: z.string().min(1).max(120), prompt: z.string().min(1).max(3000), createdAt: z.string().datetime() });
const brandKitSchema = z.object({ name: z.string().min(1).max(120), logoUrl: z.string().url().or(z.literal("")).optional(), primaryColor: z.string().regex(/^#[0-9a-fA-F]{6}$/), secondaryColor: z.string().regex(/^#[0-9a-fA-F]{6}$/), accentColor: z.string().regex(/^#[0-9a-fA-F]{6}$/), voiceTone: z.string().min(3).max(240) });
const sceneSchema = z.object({ sceneNumber: z.number().int().positive(), duration: z.number().int().min(2).max(30), visual: z.string().min(1).max(500), dialogue: z.string().max(500), onScreenText: z.string().max(200), shot: z.string().max(160), status: z.enum(["draft", "needs-review", "ready"]).default("draft") });
const platformSchema = z.enum(SOCIAL_PLATFORMS);
const durationSchema = z.union([z.literal(4), z.literal(6), z.literal(8)]);

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  studio: router({
    list: protectedProcedure.input(z.object({ projectId: z.number().optional(), useCase: z.string().optional(), days: z.number().int().min(1).max(365).optional() }).optional()).query(({ ctx, input }) => listGenerations(ctx.user.id, { projectId: input?.projectId, useCase: input?.useCase, since: input?.days ? new Date(Date.now() - input.days * 86400000) : undefined })),
    projects: protectedProcedure.query(({ ctx }) => listProjects(ctx.user.id)),
    project: protectedProcedure.input(z.object({ name: z.string().min(1).max(160), campaignNote: z.string().max(1000), progress: z.number().int().min(0).max(100).default(0) })).mutation(({ ctx, input }) => getOrCreateProject(ctx.user.id, input.name, input.campaignNote)),
    updateProject: protectedProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(1).max(160), campaignNote: z.string().max(1000), progress: z.number().int().min(0).max(100) })).mutation(({ ctx, input }) => updateProject(ctx.user.id, input.id, { name: input.name, campaignNote: input.campaignNote, progress: input.progress })),
    presets: protectedProcedure.query(({ ctx }) => listPresets(ctx.user.id)),
    brandKit: protectedProcedure.query(({ ctx }) => getBrandKit(ctx.user.id)),
    saveBrandKit: protectedProcedure.input(brandKitSchema).mutation(({ ctx, input }) => upsertBrandKit(ctx.user.id, { ...input, logoUrl: input.logoUrl || null })),
    storyboards: protectedProcedure.query(({ ctx }) => listStoryboards(ctx.user.id)),
    generateStoryboard: protectedProcedure.input(z.object({ title: z.string().min(1).max(160), brief: z.string().min(8).max(1200), projectId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const response = await invokeLLM({ messages: [{ role: "system", content: "You are an expert UGC video director. Return only valid JSON with a concise storyboard of 3 to 6 scenes, each with sceneNumber, duration, visual, dialogue, onScreenText, and shot." }, { role: "user", content: `Create a vertical UGC video storyboard from this brief: ${input.brief}` }], response_format: { type: "json_schema", json_schema: { name: "ugc_storyboard", strict: true, schema: { type: "object", properties: { scenes: { type: "array", minItems: 3, maxItems: 6, items: { type: "object", properties: { sceneNumber: { type: "integer" }, duration: { type: "integer" }, visual: { type: "string" }, dialogue: { type: "string" }, onScreenText: { type: "string" }, shot: { type: "string" } }, required: ["sceneNumber", "duration", "visual", "dialogue", "onScreenText", "shot"], additionalProperties: false } } }, required: ["scenes"], additionalProperties: false } } } }); const content = response.choices?.[0]?.message?.content; if (typeof content !== "string") throw new Error("Storyboard tidak tersedia"); const parsed = JSON.parse(content) as { scenes: unknown[] }; const scenes = z.array(sceneSchema).parse(parsed.scenes); const storyboard = await createStoryboard({ userId: ctx.user.id, projectId: input.projectId, title: input.title, brief: input.brief, scenesJson: JSON.stringify(scenes) }); const totalDuration = scenes.reduce((sum, scene) => sum + scene.duration, 0); await createVideoDraft({ userId: ctx.user.id, storyboardId: storyboard.id, title: input.title, status: "draft", scenesJson: JSON.stringify(scenes), totalDuration }); return storyboard; }),
    calendar: protectedProcedure.input(z.object({ month: z.string().regex(/^\d{4}-\d{2}$/).optional(), channel: platformSchema.optional(), status: z.enum(["draft", "scheduled", "published"]).optional() }).optional()).query(({ ctx, input }) => { const monthStart = input?.month ? new Date(`${input.month}-01T00:00:00.000Z`) : undefined; const monthEnd = monthStart ? new Date(Date.UTC(monthStart.getUTCFullYear(), monthStart.getUTCMonth() + 1, 1)) : undefined; return listCalendarItems(ctx.user.id, { monthStart, monthEnd, channel: input?.channel, status: input?.status }); }),
    notifications: protectedProcedure.input(z.object({ unreadOnly: z.boolean().default(false) }).optional()).query(({ ctx, input }) => listStudioNotifications(ctx.user.id, input?.unreadOnly ?? false)),
    markNotificationRead: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => markStudioNotificationRead(ctx.user.id, input.id)),
    platformPresets: protectedProcedure.query(({ ctx }) => listPlatformPresets(ctx.user.id)),
    savePlatformPreset: protectedProcedure.input(z.object({ platform: platformSchema, aspectRatio: z.enum(["9:16", "16:9"]), durationSeconds: durationSchema, captionTemplate: z.string().min(1).max(2000) })).mutation(({ ctx, input }) => upsertPlatformPreset(ctx.user.id, input)),
    videoDrafts: protectedProcedure.query(({ ctx }) => listVideoDrafts(ctx.user.id)),
    videoRenders: protectedProcedure.query(({ ctx }) => listVideoRenders(ctx.user.id)),
    uploadBrandLogo: protectedProcedure.input(z.object({ fileName: z.string().min(1).max(160), mimeType: z.enum(["image/png", "image/jpeg", "image/webp", "image/svg+xml"]), base64: z.string().min(20).max(10_000_000) })).mutation(async ({ ctx, input }) => { const safeName = input.fileName.replace(/[^a-zA-Z0-9._-]/g, "-"); const bytes = Buffer.from(input.base64, "base64"); const stored = await storagePut(`brand-kits/${ctx.user.id}/${safeName}`, bytes, input.mimeType); return { url: stored.url, key: stored.key }; }),
    startVideoRender: protectedProcedure.input(z.object({ prompt: z.string().min(20).max(5000), videoDraftId: z.number().int().positive().optional(), platform: platformSchema.default("Instagram Reels"), aspectRatio: z.enum(["9:16", "16:9"]).default("9:16"), durationSeconds: durationSchema.default(8) })).mutation(async ({ ctx, input }) => { const queuePosition = await getNextVideoQueuePosition(ctx.user.id); const render = await createVideoRender({ userId: ctx.user.id, videoDraftId: input.videoDraftId, operationName: `queued://${crypto.randomUUID()}`, prompt: input.prompt, platform: input.platform, aspectRatio: input.aspectRatio, durationSeconds: input.durationSeconds, queuePosition, status: "queued" }); const sessionToken = getRequestSessionToken(ctx.req); if (!render?.id) return render; if (sessionToken) { try { const job = await createHeartbeatJob({ name: `video-render-${render.id}`, cron: "0 * * * * *", path: "/api/scheduled/processVideoRender", description: `Process render video #${render.id}` }, sessionToken); await updateVideoRender(ctx.user.id, render.id, { scheduleCronTaskUid: job.taskUid }); await processVideoRenderTask(job.taskUid, sessionToken); } catch { const operation = await startVeoRender(input.prompt, input.aspectRatio, input.durationSeconds); return updateVideoRender(ctx.user.id, render.id, { operationName: operation.name, status: "rendering" }); } } return render; }),
    videoRenderStatus: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(async ({ ctx, input }) => { const render = await getVideoRender(ctx.user.id, input.id); if (!render) throw new Error("Render video tidak ditemukan"); if (render.status === "completed" || render.status === "failed") return render; if (render.scheduleCronTaskUid) { const sessionToken = getRequestSessionToken(ctx.req); if (sessionToken) { await processVideoRenderTask(render.scheduleCronTaskUid, sessionToken); return (await getVideoRender(ctx.user.id, render.id)) ?? render; } } if (render.operationName.startsWith("queued://")) return render; try { const result = await pollVeoRender(render.operationName, ctx.user.id); if (result.status === "rendering") return (await updateVideoRender(ctx.user.id, render.id, { status: "rendering", videoUrl: render.videoUrl, errorMessage: null })) ?? render; if (result.status === "failed") { const updated = (await updateVideoRender(ctx.user.id, render.id, { status: "failed", videoUrl: null, errorMessage: result.errorMessage ?? "Render gagal" })) ?? render; if (!render.notificationSentAt) { await createStudioNotification({ userId: ctx.user.id, renderId: render.id, kind: "render_failed", title: "Render video gagal", message: result.errorMessage ?? "Gemini mengembalikan error." }); await updateVideoRender(ctx.user.id, render.id, { notificationSentAt: new Date() }); } return updated; } const updated = (await updateVideoRender(ctx.user.id, render.id, { status: "completed", videoUrl: result.videoUrl, errorMessage: null })) ?? render; if (!render.notificationSentAt) { await createStudioNotification({ userId: ctx.user.id, renderId: render.id, kind: "render_completed", title: "Video MP4 siap", message: "Render Gemini Anda selesai dan siap diunduh." }); await updateVideoRender(ctx.user.id, render.id, { notificationSentAt: new Date() }); } return updated; } catch (error) { const message = error instanceof Error ? error.message : "Render video gagal"; return (await updateVideoRender(ctx.user.id, render.id, { status: "failed", videoUrl: null, errorMessage: message })) ?? render; } }),
    scheduleContent: protectedProcedure.input(z.object({ generationId: z.number().int().positive().optional(), storyboardId: z.number().int().positive().optional(), scheduledFor: z.coerce.date(), channel: z.string().min(1).max(40), caption: z.string().max(2000), status: z.enum(["draft", "scheduled", "published"]).default("scheduled") })).mutation(({ ctx, input }) => createCalendarItem({ userId: ctx.user.id, generationId: input.generationId, storyboardId: input.storyboardId, scheduledFor: input.scheduledFor, channel: input.channel, caption: input.caption, status: input.status })),
    moveCalendarItem: protectedProcedure.input(z.object({ id: z.number().int().positive(), scheduledFor: z.coerce.date().optional(), channel: z.string().min(1).max(40).optional(), status: z.enum(["draft", "scheduled", "published"]).optional() }).refine(input => input.scheduledFor || input.channel || input.status, "Perubahan kalender tidak boleh kosong")).mutation(({ ctx, input }) => updateCalendarItem(ctx.user.id, input.id, { ...(input.scheduledFor ? { scheduledFor: input.scheduledFor } : {}), ...(input.channel ? { channel: input.channel } : {}), ...(input.status ? { status: input.status } : {}) })),
    savePreset: protectedProcedure.input(z.object({ name: z.string().min(1).max(120), description: z.string().max(240), controls: controlsSchema })).mutation(({ ctx, input }) => createPreset({ userId: ctx.user.id, name: input.name, description: input.description, controlsJson: JSON.stringify(input.controls) })),
    removePreset: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => deletePreset(ctx.user.id, input.id)),
    updatePreset: protectedProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(1).max(120), description: z.string().max(240), controls: controlsSchema })).mutation(({ ctx, input }) => updatePreset(ctx.user.id, input.id, { name: input.name, description: input.description, controlsJson: JSON.stringify(input.controls) })),
    generate: protectedProcedure.input(z.object({ controls: controlsSchema, title: z.string().min(1).max(160), projectId: z.number().int().positive().optional(), framing: framingSchema.default("Potret natural"), batchId: z.string().max(64).optional(), variantIndex: z.number().int().min(1).optional(), variantCount: z.number().int().min(1).max(3).optional(), directionHistory: z.array(directionEntrySchema).max(20).optional(), brandKit: brandKitSchema.partial().optional() })).mutation(async ({ ctx, input }) => { const brandContext = input.brandKit ? ` Brand kit: ${input.brandKit.name ?? "Merek utama"}; warna utama ${input.brandKit.primaryColor ?? ""}, sekunder ${input.brandKit.secondaryColor ?? ""}, aksen ${input.brandKit.accentColor ?? ""}; gaya bahasa ${input.brandKit.voiceTone ?? ""}.` : ""; const prompt = `${buildGenerationPrompt(input.controls as StudioControls)} Framing: ${input.framing}.${brandContext}`; const result = await generateImage({ prompt, model: "MODEL_GPT_IMAGE_2", quality: "medium" }); if (!result.url) throw new Error("Image generation returned no URL"); return createGeneration({ userId: ctx.user.id, projectId: input.projectId, imageUrl: result.url, prompt, controlsJson: JSON.stringify(input.controls), title: input.title, framing: input.framing, useCase: input.controls.useCase, batchId: input.batchId, variantIndex: input.variantIndex, variantCount: input.variantCount, directionHistoryJson: JSON.stringify(input.directionHistory ?? []), brandKitJson: input.brandKit ? JSON.stringify(input.brandKit) : null }); }),
    remove: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => deleteGeneration(ctx.user.id, input.id)),
    analyzePrompt: protectedProcedure.input(z.object({ prompt: z.string().min(20).max(3000) })).mutation(({ input }) => { const checks = [{ label: "Identitas karakter", pass: /persona|kreator/i.test(input.prompt) }, { label: "Arahan visual", pass: /penampilan|kulit|rambut/i.test(input.prompt) }, { label: "Konteks adegan", pass: /latar|dapur|studio|kamar|kafe/i.test(input.prompt) }, { label: "Kebutuhan konten", pass: /ugc|testimoni|unboxing|rekomendasi/i.test(input.prompt) }, { label: "Framing", pass: /framing|potret|close-up|lifestyle|hero/i.test(input.prompt) }]; const score = Math.round((checks.filter(check => check.pass).length / checks.length) * 100); return { score, checks, suggestions: checks.filter(check => !check.pass).map(check => `Tambahkan ${check.label.toLowerCase()} agar arahan lebih konsisten.`) }; }),
    improveBrief: protectedProcedure.input(z.object({ brief: z.string().min(8).max(1200) })).mutation(async ({ input }) => { const response = await invokeLLM({ messages: [{ role: "system", content: "You are a concise UGC creative director. Turn rough briefs into practical photorealistic virtual creator image prompts. Return only valid JSON." }, { role: "user", content: `Improve this UGC brief: ${input.brief}` }], response_format: { type: "json_schema", json_schema: { name: "ugc_prompt", strict: true, schema: { type: "object", properties: { prompt: { type: "string" }, suggestions: { type: "array", items: { type: "string" } }, controls: { type: "object", properties: { persona: { type: "string" }, appearance: { type: "string" }, expression: { type: "string" }, outfit: { type: "string" }, setting: { type: "string" }, shotType: { type: "string" }, useCase: { type: "string" } }, required: ["persona", "appearance", "expression", "outfit", "setting", "shotType", "useCase"], additionalProperties: false } }, required: ["prompt", "suggestions", "controls"], additionalProperties: false } } } }); const content = response.choices?.[0]?.message?.content; if (typeof content !== "string") throw new Error("Assistant returned no prompt"); return JSON.parse(content) as { prompt: string; suggestions: string[]; controls: StudioControls }; })
  }),
});
export type AppRouter = typeof appRouter;
