import { CalendarDays, GripVertical } from "lucide-react";
import { useMemo, useState } from "react";

type CalendarItem = { id: number; scheduledFor: Date | string; channel: string; status: "draft" | "scheduled" | "published"; caption: string };
type Props = { items: CalendarItem[]; onMove: (id: number, scheduledFor: Date) => void; onUpdate: (id: number, patch: { channel?: string; status?: CalendarItem["status"] }) => void; pending?: boolean };

function dayKey(value: Date | string) { const date = new Date(value); return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`; }
function atNine(value: Date) { const date = new Date(value); date.setHours(9, 0, 0, 0); return date; }

export default function CalendarBoard({ items, onMove, onUpdate, pending }: Props) {
  const [anchor] = useState(() => atNine(new Date()));
  const days = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(anchor); date.setDate(anchor.getDate() + index); return date; }), [anchor]);
  return <div className="mt-5 overflow-x-auto pb-1"><div className="grid min-w-[760px] grid-cols-7 gap-2">{days.map(day => { const key = dayKey(day); const dayItems = items.filter(item => dayKey(item.scheduledFor) === key); return <div key={key} onDragOver={event => event.preventDefault()} onDrop={event => { const id = Number(event.dataTransfer.getData("text/calendar-id")); if (id) onMove(id, atNine(day)); }} className="min-h-36 rounded-2xl border border-[#e5eadf] bg-[#fbfcfa] p-2.5 transition-colors hover:border-[#b8cb7e] hover:bg-[#f3f8e7] dark:border-white/10 dark:bg-[#141d19] dark:hover:bg-[#263421]"><div className="flex items-center justify-between gap-2"><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#8ca93a]">{day.toLocaleDateString("id-ID", { weekday: "short" })}</p><p className="text-sm font-semibold">{day.getDate()}</p></div><CalendarDays size={14} className="text-[#a4b19e]" /></div><div className="mt-3 space-y-2">{dayItems.map(item => <div key={item.id} draggable onDragStart={event => event.dataTransfer.setData("text/calendar-id", String(item.id))} className="cursor-grab rounded-xl border border-[#e1e8dc] bg-white p-2 shadow-sm active:cursor-grabbing dark:border-white/10 dark:bg-[#18221e]"><div className="flex items-start gap-1.5"><GripVertical size={13} className="mt-0.5 shrink-0 text-[#b0bcae]" /><div className="min-w-0"><p className="truncate text-[10px] font-semibold text-[#526159] dark:text-[#d9e6d3]">{item.caption || "Konten baru"}</p><select value={item.channel} onChange={event => onUpdate(item.id, { channel: event.target.value })} onClick={event => event.stopPropagation()} className="mt-1 w-full rounded-md border-0 bg-transparent p-0 text-[9px] text-[#8a968f] outline-none"><option>Instagram Reels</option><option>TikTok</option><option>YouTube Shorts</option><option>LinkedIn</option></select><select value={item.status} onChange={event => onUpdate(item.id, { status: event.target.value as CalendarItem["status"] })} onClick={event => event.stopPropagation()} className="mt-1 w-full rounded-md border-0 bg-transparent p-0 text-[9px] text-[#8a968f] outline-none"><option value="draft">Draf</option><option value="scheduled">Terjadwal</option><option value="published">Terbit</option></select></div></div></div>)}{!dayItems.length && <p className="pt-4 text-center text-[10px] text-[#a5afa9]">Lepas konten di sini</p>}</div></div>; })}</div>{pending && <p className="mt-2 text-[11px] text-[#8ca93a]">Menyimpan perubahan jadwal…</p>}</div>;
}
