import { Download, Film, Loader2, Play, Sparkles, TriangleAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Props = { prompt: string; videoDraftId?: number; platform: "Instagram Reels" | "TikTok" | "YouTube Shorts" | "LinkedIn"; aspectRatio: "9:16" | "16:9"; durationSeconds: 4 | 6 | 8 };

export default function VideoRenderPanel({ prompt, videoDraftId, platform, aspectRatio, durationSeconds }: Props) {
  const [renderId, setRenderId] = useState<number>();
  const start = trpc.studio.startVideoRender.useMutation({ onSuccess: data => { setRenderId(data?.id); toast.success("Render video dimulai"); }, onError: error => toast.error(error.message) });
  const status = trpc.studio.videoRenderStatus.useQuery({ id: renderId! }, { enabled: Boolean(renderId), refetchInterval: query => query.state.data?.status === "completed" || query.state.data?.status === "failed" ? false : 5000 });
  const render = status.data;
  const processing = start.isPending || (Boolean(renderId) && render?.status !== "completed" && render?.status !== "failed");
  const startRender = () => { if (!prompt.trim()) return toast.error("Arahan video belum tersedia"); start.mutate({ prompt, videoDraftId, platform, aspectRatio, durationSeconds }); };
  return <div className="mt-5 rounded-2xl border border-[#dfe8d6] bg-[#f8fbf4] p-4 dark:border-white/10 dark:bg-[#1b2a20]"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#8ca93a]"><Film size={14} /> Render video MP4</div><h3 className="mt-1 text-sm font-semibold">Ubah storyboard menjadi video siap unduh.</h3><p className="mt-1 text-[11px] leading-5 text-[#7b887f]">Gemini Veo membuat draf {aspectRatio} selama {durationSeconds} detik dengan audio native bila tersedia.</p></div><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold text-[#738c2c] dark:bg-[#263421]">{platform}</span></div>{processing && <div className="mt-4 flex items-center gap-3 rounded-xl bg-white p-3 dark:bg-[#18221e]"><span className="relative flex size-8 items-center justify-center rounded-full bg-[#e9f4bd] text-[#718b2b] dark:bg-[#34442b]"><Loader2 size={16} className="animate-spin" /><span className="absolute inset-0 animate-ping rounded-full bg-[#d6f37b]/30" /></span><div><p className="text-xs font-semibold">{start.isPending ? "Menghubungkan ke Gemini…" : render?.status === "queued" ? `Menunggu antrean${render.queuePosition ? ` · posisi ${render.queuePosition}` : ""}…` : "Gemini sedang merender video…"}</p><p className="mt-0.5 text-[10px] text-[#89968e]">Status diperbarui otomatis setiap beberapa detik.</p></div></div>}{render?.status === "failed" && <div className="mt-4 flex gap-2 rounded-xl bg-[#fff1ec] p-3 text-[#a4513b] dark:bg-[#3a2520]"><TriangleAlert size={16} className="mt-0.5 shrink-0" /><div><p className="text-xs font-semibold">Render belum berhasil</p><p className="mt-1 text-[10px] leading-4">{render.errorMessage ?? "Gemini mengembalikan error yang tidak diketahui."}</p></div></div>}{render?.status === "completed" && render.videoUrl && <div className="mt-4 overflow-hidden rounded-xl bg-black"><video controls playsInline className="mx-auto max-h-[420px] w-full object-contain" src={render.videoUrl} /><a href={render.videoUrl} download="omni-studio-ugc.mp4" className="flex items-center justify-center gap-2 bg-[#17211e] px-4 py-3 text-xs font-semibold text-white dark:bg-[#d6f37b] dark:text-[#17211e]"><Download size={14} /> Unduh video MP4</a></div>} {!processing && render?.status !== "completed" && <button onClick={startRender} disabled={start.isPending} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#17211e] px-4 py-2.5 text-xs font-semibold text-white transition hover:-translate-y-0.5 dark:bg-[#d6f37b] dark:text-[#17211e]"><Sparkles size={14} /> {render?.status === "failed" ? "Coba render lagi" : <><Play size={13} /> Render video sekarang</>}</button>}</div>;
}
